# Generated by Django 3.2.8 on 2021-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_description_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
